version: "3"
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis-cache:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6380:6379"